const industryList = [
    { name: 'AGRICULTURE AND ALLIED INDUSTRIES',checked: false },
    { name: 'AUTOMOBILES', checked: false },
    { name: 'AUTO COMPONENTS', checked: false },
    { name: 'AVIATION', checked: false },
    { name: 'BANKING', checked: false },
    { name: 'CEMENT', checked: false },
    { name: 'CONSUMER DURABLES', checked: false },
    { name: 'ECOMMERCE', checked: false },
    { name: 'EDUCATION AND TRAINING', checked: false },
    { name: 'ENGINEERING AND CAPITAL GOODS', checked: false },
    { name: 'FINANCIAL SERVICES', checked: false },
    { name: 'FMCG', checked: false },
    { name: 'GEMS AND JEWELLERY', checked: false },
    { name: 'HEALTHCARE', checked: false },
    { name: 'INFRASTRUCTURE', checked: false },
    { name: 'INSURANCE', checked: false },
    { name: 'IT & ITES', checked: false },
    { name: 'MANUFACTURING', checked: false },
    { name: 'MEDIA AND ENTERTAINMENT', checked: false },
    { name: 'METALS AND MINING', checked: false },
    { name: 'OIL AND GAS', checked: false },
    { name: 'PHARMACEUTICALS', checked: false },
    { name: 'PORTS', checked: false },
    { name: 'POWER', checked: false },
    { name: 'RAILWAYS', checked: false },
    { name: 'REAL ESTATE', checked: false },
    { name: 'RENEWABLE ENERGY', checked: false },
    { name: 'RETAIL', checked: false },
    { name: 'ROADS', checked: false },
    { name: 'SCIENCE AND TECHNOLOGY', checked: false },
    { name: 'SERVICES', checked: false },
    { name: 'STEEL', checked: false },
    { name: 'TELECOMMUNICATIONS', checked: false },
    { name: 'TEXTILES', checked: false },
    { name: 'TOURISM AND HOSPITALITY', checked: false },
    { name: 'OTHERS', checked: false },
]

export default industryList;